#kivy `1.10.0`
#: import main test3
<Test>:
    orientation: "vertical"
    padding: 10
    spacing: 10
    name_input: name
    url_input: url
    BoxLayout:
        size_hint_y:None
        height: "40dp"
        Label:
            text: 'Name'
        TextInput:
            id: name
        Label:
            text: 'Weblink'
        TextInput:
            id: url
    BoxLayout:
        size_hint_y:None
        height: "40dp"
        Button:
            text: 'Submit'
            size_hint_x: 15
            on_press: root.submit_manga()
        Button:
            text: 'Delete'
            size_hint_x: 15
            on_press: root.delete_manga()

        Button:
            text: 'Replace'
            size_hint_x: 15
            on_press: root.replace_manga()

    ScrollView:
        size_hint: (1, 1)
        height: 60
        
        GridLayout:
            id: grid
            size_hint_y: None
            size_hint_x: 1
            height: self.minimum_height
            cols: 2
            Label:
                text:'col 1'
            Label:
                text:'col 2'
            