#kivy `1.10.0`
#: import ListAdapter kivy.adapters.listadapter.ListAdapter
#: import ListItemButton kivy.uix.listview.ListItemButton
#: import main test2
<RootWidget>
    orientation: "vertical"
    name_input: name
    url_input: url
    manga_list: manga_list_view
    padding: 10
    spacing: 10
    BoxLayout:
        size_hint_y:None
        height: "40dp"
        Label:
            text: 'Name'
        TextInput:
            id: name
        Label:
            text: 'Weblink'
        TextInput:
            id: url
    
    BoxLayout:
        size_hint_y:None
        height: "40dp"
        Button:
            text: 'Submit'
            size_hint_x: 15
            on_press: root.submit_manga()
        Button:
            text: 'Delete'
            size_hint_x: 15
            on_press: root.delete_manga()

        Button:
            text: 'Replace'
            size_hint_x: 15
            on_press: root.replace_manga()

    ListView:
        id: manga_list_view
        adapter:
            ListAdapter(data=["Luffy RULEZ"], cls= main.MangaListButton)
