#kivy `1.10.0`
<RootWidget>
    canvas:
        Color:
            rgb: 1, 0, 0
        
    BoxLayout:
        orientation: 'vertical'
        size_hint: .2, .3
        pos:(20, 300)
        Label:
            text: 'Name'
        TextInput:
            id: user_input
            text: 'Name'
        Label:
            text: 'Weblink'
            size_hint: .9, .9
        TextInput:
            id: user_input
            text: 'Weblink'
        Label:
            text: 'Summary'
            size_hint: .9, .9
        TextInput:
            id: user_input
            text: 'Summary'
    
    BoxLayout:
        size_hint: .2, .2
        Button:
            text: 'Test'
    
    GridLayout:
        id: grid
        cols: 1
        rows: root.zach_list
        